# 🔍 DIGITAL FORENSICS & INCIDENT RESPONSE (DFIR): Complete Guide for Blue Team

## Understanding The Investigation Discipline

---

## 📖 What is DFIR?

**In 60 seconds:**
DFIR = **Digital Forensics** + **Incident Response**

- **Digital Forensics**: Post-attack investigation. "What exactly happened? Where's the evidence?"
- **Incident Response**: During/after attack. Contain the bleeding, eradicate threats, recover systems.

**Key Distinction:**
```
SOC/Detection Engineer → Detects attack is happening → "ALERT!"
Incident Responder → Gets alert → Makes decisions in real-time → "Isolate server NOW"
DFIR Analyst → After containment → Deep investigation → "Here's what happened"
```

**Timeline view:**
```
Attacker enters → SOC detects → IR responds/contains → DFIR investigates → Report + Prevention
      (0h)            (5min)          (30min)              (hours/days)       (recommendations)
```

---

## 🎯 Why Does a Blue Team Professional Need DFIR?

### Real Job Scenarios

| Scenario | What Happens |
|----------|--------------|
| Ransomware hits company | IR contains it. DFIR figures out how they got in, what they encrypted, how to prevent next time |
| Data breach detected | IR isolates systems. DFIR answers: "What was stolen? When? How much?" |
| Insider threat suspected | IR doesn't know if it's real. DFIR proves it with file timestamps, access logs, email trails |
| Malware outbreak | IR removes it. DFIR traces patient zero: first infected machine, lateral movement path |
| Compliance audit | "Did you detect this attack?" DFIR produces timeline + evidence as proof |

### Interview Questions You'll Face

1. **"Walk me through a forensic investigation you've done"**
   - Expected: Timeline structure, tools used, evidence collected, conclusions

2. **"What's the difference between 'root cause' and 'first suspicious log'?"**
   - Expected: Root cause = first action that succeeded (initial access). First log = detection of that action.

3. **"How do you preserve evidence chain of custody?"**
   - Expected: Hashing, imaging, documentation, no data modification

4. **"You find an encrypted file on a compromised server. How do you proceed?"**
   - Expected: Image it, hash it, don't decrypt (preserves evidence), analyze offline

---

## 🔍 The Concept Broken Down

### Part 1: The DFIR Team & Roles

```
SECURITY OPERATIONS CENTER (SOC)
│
├─ SIEM Analyst
│  ├─ Monitors alerts
│  ├─ Sees "100 failed logins to Domain Admin in 5 minutes"
│  └─ Escalates to Incident Response
│
├─ Detection Engineer
│  ├─ Built the rule that fired
│  └─ Later uses DFIR findings to improve detection
│
└─ Incident Response Team
   ├─ Gets alert from SOC
   ├─ Decides: "Isolate compromised server NOW"
   ├─ Preserves evidence (don't wipe disk yet!)
   ├─ Collects memory dump while system is running
   └─ Calls in DFIR Analyst once system is isolated
   
   └─ DFIR Analyst (joins investigation)
      ├─ Takes over evidence
      ├─ Images disks (forensic copy)
      ├─ Analyzes offline
      ├─ Builds timeline
      ├─ Identifies root cause
      ├─ Documents attack chain
      └─ Produces report for IR + Detection Engineering
```

### Part 2: Root Cause vs First Log vs First Suspicious Movement

**This is critical. Most people get this wrong.**

```
Timeline example: Ransomware outbreak on Server-DB-01

┌─ 2024-01-15 08:00:00 ─ Admin creates backup (legitimate)
├─ 2024-01-15 08:15:00 ─ FIRST LOG GENERATED BY ATTACKER SESSION
│                         (User "john" logs in from external IP 203.0.113.45)
│                         [SOC doesn't know yet, it's not flagged]
├─ 2024-01-15 08:30:00 ─ Attacker enumerates shares (net view)
├─ 2024-01-15 09:00:00 ─ Attacker escalates to SYSTEM via CVE-2021-1732
│
└─ 2024-01-15 09:15:00 ─ FIRST SUSPICIOUS MOVEMENT DETECTED
                         (Ransomware executable dropped in C:\Windows\Temp)
                         [SOC detects unusual file access pattern]

ROOT CAUSE = 2024-01-15 08:00:00? NO
ROOT CAUSE = 2024-01-15 08:15:00? NO
ROOT CAUSE = 2024-01-15 09:15:00? NO

ROOT CAUSE = The unpatched CVE-2021-1732 on Server-DB-01
             OR weak credential "john" was using
             OR initial access method (phishing email to john? RDP exposed?)

What you MUST understand:
- First log ≠ root cause (it's just when attacker started leaving traces)
- First suspicious movement ≠ root cause (it's when we detected something)
- Root cause = first action that succeeded (initial access or privilege escalation)
```

### Part 3: Chain of Custody (CoC)

**Why this matters:**
If evidence is compromised, it's inadmissible in court AND unreliable for technical analysis.

```
DFIR Evidence Handling:

Step 1: PRESERVATION
├─ Don't touch the evidence
├─ No "rm", no "del", no modifications
├─ If possible, isolate from network (air-gap)
└─ Document who touched what, when

Step 2: COLLECTION
├─ Image disk (bit-for-bit copy)
├─ Hash original disk (SHA256)
├─ Hash image (must match exactly)
├─ Memory dump (while running, if possible)
├─ Network logs, logs from SIEM
├─ Email headers, browser history
└─ Document everything with timestamps

Step 3: ANALYSIS
├─ Work on COPY, never original
├─ All actions logged (tool output, not just "I found it")
├─ Keep audit trail of who accessed evidence
└─ Don't modify anything

Step 4: DOCUMENTATION
├─ Hash verification (original vs copy matches)
├─ Chain of custody form signed by all handlers
├─ Detailed notes of findings
├─ Reproducibility (another analyst could repeat your steps)
└─ Legal compliance (if needed for court)

EXAMPLE CoC:

Evidence Item: Server-DB-01 Primary Drive
Original Hash: SHA256:a1b2c3d4e5f6...
Image Hash:   SHA256:a1b2c3d4e5f6... ✓ MATCH

Collected by: Jane Analyst (2024-01-15 14:00:00 UTC)
Sealed by: John Manager (2024-01-15 14:30:00 UTC)
Analyzed by: Sarah DFIR (2024-01-16 09:00:00 UTC)
```

### Part 4: Evidence Sources in DFIR

```
Where evidence lives:

┌─ DISK EVIDENCE
│  ├─ File system (NTFS, ext4, etc)
│  ├─ Master File Table (MFT) - contains ALL file metadata
│  ├─ Deleted files (still in unallocated space)
│  ├─ Registry hives (Windows config + user activity)
│  ├─ Logs (Windows Event Logs, application logs, web server logs)
│  ├─ Prefetch files (programs that were executed)
│  └─ Browser history, cache, cookies
│
├─ MEMORY EVIDENCE
│  ├─ RAM at moment of compromise (volatile!)
│  ├─ Running processes
│  ├─ Network connections
│  ├─ Encryption keys in memory
│  ├─ Malware behavior (before it hit disk)
│  └─ Password hashes
│
├─ NETWORK EVIDENCE
│  ├─ Firewall logs (blocked/allowed connections)
│  ├─ Network IDS/IPS signatures
│  ├─ DNS query logs (what domains did attacker query?)
│  ├─ Netflow/syslog (traffic patterns)
│  └─ Proxy logs (web traffic)
│
└─ APPLICATION EVIDENCE
   ├─ Email headers (where did phishing come from?)
   ├─ Web server access logs (what was accessed?)
   ├─ Database logs (what queries were executed?)
   ├─ VPN connection logs (who connected from where?)
   └─ Authentication logs (successful + failed logins)
```

---

## ⚙️ The DFIR Investigation Process (Step-by-Step)

### Phase 1: Incident Scoping

**Question to answer:** "How bad is this really?"

```
When DFIR gets called in:

1. Understand what IR already did
   ├─ Which systems are isolated?
   ├─ Which are still live?
   ├─ Was memory dumped? From which systems?
   └─ What data is available?

2. Interview Incident Responder
   ├─ "When was the alert triggered?"
   ├─ "What was the observable that alerted?"
   ├─ "What did you do to contain?"
   └─ "What windows of opportunity to collect evidence remain?"

3. Identify systems of interest
   ├─ Patient zero (first compromised system)
   ├─ Lateral movement path
   ├─ Data exfiltration endpoints
   └─ Command & control contact points

4. Create initial hypothesis
   ├─ "Attacker used phishing → initial access → escalated → lateral movement"
   ├─ OR "Vulnerability exploit → reverse shell → persistence"
   └─ "We'll test this hypothesis with evidence"
```

### Phase 2: Evidence Collection

**Golden Rule:** Collect from volatile to non-volatile

```
Why this order?
- Memory (volatile) = disappears on reboot
- Disk (non-volatile) = survives reboot
- Network (semi-volatile) = logs rotate, get overwritten

Collection priority:

STEP 1: VOLATILE (do first, it'll be gone soon)
├─ Memory dump (if system still running)
│  └─ Tool: DumpIt, Belkasoft RAM Capturer, WinPmem
├─ Current network connections
│  └─ Command: netstat -ano (Windows) or netstat -tulpn (Linux)
├─ Running processes
│  └─ Command: tasklist /v (Windows) or ps aux (Linux)
└─ Open files
   └─ Command: Handle, lsof

STEP 2: NON-VOLATILE (after volatile is captured)
├─ Disk imaging
│  └─ Tool: FTK Imager, Guymager, dd
├─ Event logs
│  └─ Location: C:\Windows\System32\winevt\Logs (Windows)
├─ Registry hives
│  └─ Location: C:\Users\*\NTUSER.DAT (Windows)
└─ Application logs
   └─ Location: Varies (Apache, IIS, SQL Server, etc)

STEP 3: NETWORK LOGS (already collected by IR, verify completeness)
├─ Firewall logs (from when?)
├─ IDS/IPS alerts (timeframe?)
├─ DNS logs (available?)
└─ Proxy logs (retention period?)
```

### Phase 3: Timeline Construction

**This is the HEART of DFIR.**

```
Building a master timeline means:
- Collecting timestamps from multiple sources
- Merging into single chronological view
- Identifying patterns and sequences

Timeline sources:

1. FILE SYSTEM TIMESTAMPS
   ├─ Created (C) = file creation
   ├─ Accessed (A) = file last opened (or read)
   ├─ Modified (M) = file content changed
   └─ Changed (Ch) = metadata changed (permissions, etc)
   
   Tool: FTK Imager, Timeline Explorer, PowerShell

2. WINDOWS EVENT LOGS
   ├─ EventID 4624 = Logon (successful)
   ├─ EventID 4625 = Logon Failed
   ├─ EventID 4688 = Process creation
   ├─ EventID 4720 = User account created
   ├─ EventID 4728 = User added to admin group
   └─ EventID 4656 = Object (file/registry) accessed
   
   Tool: Event Log Explorer, Windows Event Viewer, Splunk

3. REGISTRY TIMESTAMPS
   ├─ LastWrite timestamps on registry keys
   ├─ MRU (Most Recently Used) lists
   ├─ Run/RunOnce keys (persistence mechanisms)
   └─ USB device history (tracking connected devices)
   
   Tool: RegRipper, Registry Explorer, PowerShell

4. APPLICATION LOGS
   ├─ Web server access logs (IIS, Apache)
   ├─ Database logs (SQL Server, MySQL)
   ├─ Email logs (Exchange, Gmail)
   └─ Antivirus logs (when did AV detect malware?)

5. PREFETCH & RECENT FILES
   ├─ Prefetch = programs that were executed + execution count + timestamps
   ├─ LnkFiles (shortcuts) = when was file accessed
   └─ RecentFileCache = what was recently opened
   
   Tool: Registry Explorer, Nirsoft utilities

BUILDING THE TIMELINE:

Raw events from multiple sources:
├─ 2024-01-15 08:15:22 → EventID 4624: User "john" logged in from 203.0.113.45
├─ 2024-01-15 08:16:45 → netstat log: connection established to C2 (103.145.23.67:4444)
├─ 2024-01-15 08:17:00 → File created: C:\Temp\update.exe (attacker payload)
├─ 2024-01-15 08:30:15 → EventID 4688: powershell.exe executed by "john"
├─ 2024-01-15 08:31:22 → Registry key modified: HKLM\Software\...\Run (persistence)
└─ 2024-01-15 09:15:00 → Ransomware executable detected on disk

Timeline interpretation:
1. Initial access via john's account (8:15)
2. Established C2 connection (8:16)
3. Dropped payload (8:17)
4. Executed payload via PowerShell (8:30)
5. Established persistence (8:31)
6. Started encryption (9:15)

ROOT CAUSE: john's account was compromised (weak password? phishing?)
```

### Phase 4: Root Cause Analysis

**Question:** "How did the attacker get in?"

```
Working backwards from the timeline:

Ransomware detected at 09:15
    ↑
Payload executed at 08:30 (by john)
    ↑
Payload uploaded at 08:17 (by john)
    ↑
C2 connection established at 08:16 (by john)
    ↑
John logged in from external IP at 08:15
    ↑
ROOT CAUSE: john's credentials were compromised

Next question: HOW were john's credentials compromised?
├─ Phishing email (check email logs, browser history)
├─ Credential stuffing (check john's password history)
├─ Weak password guessed (policy check)
├─ Keylogger installed (check for malware on john's workstation)
└─ VPN credentials stolen (check VPN access logs)

Investigation example:

HYPOTHESIS 1: Phishing
├─ Check john's email for suspicious message
├─ Look for attachment download
├─ Check browser history for malicious domain
└─ If found → "john clicked phishing link, unknowingly gave credentials"

HYPOTHESIS 2: Credential Stuffing (attacker tried common passwords)
├─ Check Event Log 4625 (failed logins) before 08:15
├─ Count: 47 failed attempts in 10 minutes to "john" account
├─ Source IP: same as 08:15 successful login (203.0.113.45)
└─ Conclusion → "Attacker brute-forced john's password successfully"

HYPOTHESIS 3: Weak Password
├─ Password policy check: "Password minimum 8 chars, no complexity required"
├─ Password history: john hasn't changed password in 2 years
├─ Conclusion → "Weak/old password vulnerable to guess"
```

### Phase 5: Impact Analysis

**Question:** "What did the attacker do? What was affected?"

```
Answering these questions:

1. What was accessed?
   ├─ File access logs (which directories opened?)
   ├─ Database logs (which tables queried?)
   ├─ Email logs (which mailboxes accessed?)
   └─ Conclusion: "Attacker accessed Financial_Data folder + Customer_Database"

2. What was stolen?
   ├─ Files copied to attacker machine (network logs show exfiltration)
   ├─ Data volume (100GB? 1GB? 10MB?)
   ├─ Sensitivity (PII? financial? trade secrets?)
   └─ Conclusion: "Customer database (5GB, contains SSN/Credit Card) exfiltrated"

3. What was modified?
   ├─ Ransomware encrypted (how many files?)
   ├─ Backdoors installed (where? what?)
   ├─ Persistence mechanisms (registry edits? scheduled tasks?)
   └─ Conclusion: "47,230 files encrypted. Backdoor in System32. Persistence in Run key"

4. What systems were affected?
   ├─ Patient zero: Server-DB-01
   ├─ Lateral movement to: Server-APP-02, Server-APP-03, Workstation-john
   └─ Conclusion: "4 systems compromised in 45 minutes"

5. How long was attacker present?
   ├─ First log: 08:15
   ├─ Last C2 contact: 09:15
   ├─ But was there persistence? (backdoor may be active)
   └─ Conclusion: "Active intrusion 1 hour. Backdoor unknown if still active"
```

### Phase 6: Report Generation

**What the report must contain:**

```
DFIR INVESTIGATION REPORT STRUCTURE

1. EXECUTIVE SUMMARY
   ├─ What happened in 2 paragraphs
   ├─ Impact summary (systems, data, duration)
   └─ Recommendations (prevent, detect, respond)

2. TIMELINE OF EVENTS
   ├─ Chronological list with timestamps
   ├─ Evidence source for each event
   ├─ Interpretation of each event
   └─ Visual representation (Gantt chart or text diagram)

3. ROOT CAUSE ANALYSIS
   ├─ Initial access method (phishing? exploit? brute force?)
   ├─ Evidence supporting conclusion
   ├─ Why this method worked (vulnerability, weakness, oversight?)
   └─ Lessons learned

4. ATTACK CHAIN (MITRE ATT&CK MAPPING)
   ├─ Initial Access (T1566 = Phishing)
   ├─ Credential Access (T1110 = Brute Force)
   ├─ Persistence (T1547.001 = Registry Run Key)
   ├─ Privilege Escalation (T1548 = CVE-2021-1732)
   ├─ Defense Evasion (T1036 = Masquerading)
   ├─ Lateral Movement (T1570 = Lateral Tool Transfer)
   ├─ Exfiltration (T1041 = Exfiltration Over C2)
   └─ Impact (T1486 = Data Encrypted for Impact)

5. EVIDENCE COLLECTED
   ├─ Memory dump (size, hash, analysis findings)
   ├─ Disk image (size, hash, analysis findings)
   ├─ Logs collected (which? date range? gaps?)
   └─ Chain of custody (signed & verified)

6. FORENSIC FINDINGS
   ├─ Executable files found (malware hashes, YARA signatures)
   ├─ Registry modifications (persistence mechanisms)
   ├─ File system analysis (deleted files recovered, timestamps)
   ├─ Memory analysis (injected code, malware in RAM)
   └─ Network artifacts (C2 IPs, DNS queries, exfiltration patterns)

7. IMPACT SUMMARY
   ├─ Systems compromised (list)
   ├─ Data affected (types, volume, sensitivity)
   ├─ Services disrupted (for how long?)
   ├─ Recovery time (how long to eradicate + restore?)
   └─ Estimated losses (if relevant)

8. RECOMMENDATIONS
   ├─ IMMEDIATE (fix the bleeding):
   │  └─ "Patch CVE-2021-1732 on all Windows systems"
   ├─ SHORT-TERM (prevent recurrence):
   │  ├─ "Implement MFA on all user accounts"
   │  ├─ "Deploy application whitelisting"
   │  └─ "Segment network to isolate critical systems"
   ├─ MEDIUM-TERM (improve detection):
   │  ├─ "Implement new detection rule for anomalous C2 connections"
   │  └─ "Deploy EDR (Endpoint Detection & Response)"
   └─ LONG-TERM (holistic improvement):
      ├─ "Security awareness training (phishing simulation)"
      ├─ "Zero Trust Architecture implementation"
      └─ "Tabletop exercises quarterly"

9. APPENDICES
   ├─ Raw timeline data (sortable)
   ├─ Malware analysis report
   ├─ Registry dumps
   ├─ File listings
   └─ Chain of custody documentation
```

---

## 🛠️ DFIR Tools You Must Know

### Essential Tools by Category

**DISK IMAGING & HASHING:**
```
FTK Imager
├─ Windows, Mac, Linux
├─ Create forensic images (E01, dd, AFF formats)
├─ Hash verification (MD5, SHA1, SHA256)
├─ File recovery from unallocated space
└─ FREE

Guymager
├─ Linux-based
├─ Faster imaging than FTK on Linux
├─ AES encryption support
└─ FREE

dd (command-line)
├─ Linux/Mac
├─ if=/dev/sda of=/media/usb/disk.img (full disk image)
├─ if=/dev/sda1 of=/media/usb/partition.img (single partition)
└─ FREE
```

**MEMORY ANALYSIS:**
```
Volatility 3
├─ Windows, Mac, Linux memory analysis
├─ Find running processes, injected code, network connections
├─ Extract malware from RAM
├─ pslist, pstree, netscan, yarascan (key commands)
└─ FREE

DumpIt / Belkasoft RAM Capturer
├─ Quick memory dumps from running systems
├─ Before shutting down (preserve volatile evidence!)
└─ FREE/Commercial
```

**TIMELINE CONSTRUCTION:**
```
Plaso (log2timeline)
├─ Linux-based
├─ Parses events from disk image + logs
├─ Outputs to CSV/timeline
└─ FREE

Timeline Explorer (SANS)
├─ Windows GUI
├─ Import/filter/search timelines
├─ Color-code events
└─ FREE

Autopsy
├─ Visual forensic platform
├─ Disk image analysis
├─ Timeline generation
├─ Keyword search
└─ FREE
```

**REGISTRY ANALYSIS:**
```
RegRipper
├─ Windows registry analysis
├─ Extract Run keys, MRU lists, USB history
├─ Plugins for each analysis type
└─ FREE

Registry Explorer (Eric Zimmerman)
├─ Modern registry viewer
├─ Timeline from registry LastWrite times
├─ Search across all hives
└─ FREE
```

**LOG ANALYSIS:**
```
Windows Event Log Parser
├─ Parse .evtx files offline
├─ Filter by EventID, timestamp, user
├─ Export to CSV
└─ FREE (built-in or powershell)

Splunk / ELK / GreyLog
├─ Aggregate logs from multiple sources
├─ Search + pivot
├─ Create timelines from log timestamps
└─ Commercial/FREE (ELK)
```

**PRACTICAL EXAMPLE:**

```
Investigation workflow using tools:

1. Image compromised disk
   └─ FTK Imager: Create E01 image, verify hash

2. Extract memory dump (if still running)
   └─ DumpIt: Capture RAM before shutdown

3. Mount forensic image (read-only)
   └─ FTK Imager or loopback mount

4. Parse events from image
   └─ Plaso: Extract all timestamps into CSV

5. Analyze memory dump
   └─ Volatility: volatility3 -f memory.dump windows.pslist
      (find suspicious processes, injected code)

6. Extract registry hives
   └─ RegRipper: rip.pl -r C:\Windows\System32\config\SYSTEM
      (extract Run keys, last login time, etc)

7. Build master timeline
   └─ Timeline Explorer: Import CSV from Plaso, add manual entries from Volatility/RegRipper

8. Analyze timeline
   ├─ Look for sequences (login → payload → execution → persistence)
   ├─ Cross-reference with network logs (did attacker C2?)
   └─ Identify root cause

9. Generate report
   └─ Document findings with evidence + hashes + screenshots
```

---

## 📊 Real Investigation Example: Step-by-Step

**Scenario: Ransomware on File Server**

```
TIMELINE OF INVESTIGATION:

2024-01-15 14:00:00 (Investigation starts)
├─ SOC detected 10,000 files encrypted on FILE-SERVER-01
├─ Incident Response immediately isolated server (network disconnected)
└─ DFIR analyst called in to investigate

2024-01-15 14:30:00 (DFIR arrives)
├─ Collects memory dump (system still running, RAM has evidence)
├─ Initiates disk imaging (FTK Imager)
└─ Documents chain of custody

2024-01-15 18:00:00 (Analysis begins)
├─ Volatility analysis of memory:
│  └─ Finds suspicious process: rundll32.exe (usually legitimate, but running from Temp)
│  └─ Extracts injected code (looks like C2 beacon)
│
├─ Disk image analysis:
│  ├─ Find files in C:\Temp\update.exe (dropped 2024-01-15 08:17)
│  ├─ Find files in C:\Users\john\AppData\Roaming (attacker staging area)
│  └─ MFT analysis shows file creation timestamps
│
└─ Registry analysis:
   ├─ HKLM\Software\...\Run contains "C:\Temp\update.exe"
   ├─ LastWrite timestamp: 2024-01-15 08:31
   └─ This is persistence mechanism

2024-01-15 22:00:00 (Timeline construction)
├─ Master timeline built:
│  ├─ 2024-01-15 08:15:22 → EventID 4624: john logged in from 203.0.113.45 ✓
│  ├─ 2024-01-15 08:16:45 → Network: connection to 198.51.100.50:4444 (C2 IP) ✓
│  ├─ 2024-01-15 08:17:00 → File created: update.exe ✓
│  ├─ 2024-01-15 08:30:15 → EventID 4688: rundll32.exe executed (loading update.exe) ✓
│  ├─ 2024-01-15 08:31:22 → Registry modified: Run key added ✓
│  └─ 2024-01-15 09:15:00 → Encryption starts ✓

2024-01-16 08:00:00 (Root cause analysis)
├─ How did john's account get compromised?
│  ├─ Check john's email → Found phishing email with subject "Urgent: Security Update"
│  ├─ Email was from attacker@phishsite.com (spoofed)
│  ├─ john clicked link, entered credentials
│  └─ ROOT CAUSE IDENTIFIED: Phishing attack
│
└─ Lateral movement?
   ├─ Check network logs → john's account (now compromised) accessed other shares
   ├─ Found: john accessed \FILE-SERVER-01\Financial_Data (unusual)
   ├─ john normally only accesses HR_Data
   └─ Lateral movement confirmed

2024-01-16 14:00:00 (Report generation)
├─ Report delivered:
│  ├─ Executive Summary: "Ransomware attack via phishing email to john@company.com"
│  ├─ Timeline: 08:15 initial access → 09:15 encryption starts (60 min intrusion window)
│  ├─ Impact: 47,230 files encrypted, Financial_Data folder accessed, 2.3 GB data possibly exfiltrated
│  ├─ Root Cause: Phishing email, john's weak password (no MFA), insufficient network segmentation
│  │
│  └─ Recommendations:
│     ├─ IMMEDIATE: Restore from backup (28 hours to restore all data)
│     ├─ SHORT: Implement MFA on all accounts
│     ├─ MEDIUM: Deploy EDR on all endpoints
│     ├─ LONG: Network segmentation (Financial_Data on isolated VLAN)
│     └─ Training: Phishing awareness for all staff (john was vector)

DETECTION ENGINEERING FOLLOW-UP:
├─ New rule needed: Detect "User account doing unusual file access outside their normal folder"
├─ john normally accesses \\HR_DATA\*
├─ john accessing \\FINANCIAL_DATA\* is anomaly
├─ Rule: EventID 5145 (file access) + john + /Financial_Data + NOT in last 90 days
├─ Alert on first occurrence
└─ This could have prevented 47,230 encrypted files
```

---

## ❌ Common Mistakes DFIR Analysts Make

### Mistake #1: Modifying Evidence

```
❌ WRONG:
"I need to see what's in this file, let me open it with Notepad"
(File timestamps change, content might be modified by OS)

✅ RIGHT:
"I'll use FTK Imager or HexDump to view file content WITHOUT modifying it"
(Read-only access, timestamps preserved)

Consequence: Modified evidence = inadmissible in court, unreliable analysis
```

---

### Mistake #2: Confusing Timeline Sequences

```
❌ WRONG:
"Process X.exe ran, so X.exe must be the malware"
(Maybe X.exe is legitimate, malware injected into it)

✅ RIGHT:
"Process X.exe ran. Did it create files? Connect to network? Modify registry?
Let me correlate all events around X.exe's execution timestamp"
(Multi-source timeline tells the real story)

Consequence: Wrong conclusion, misses actual malware, false accusation of legitimate tool
```

---

### Mistake #3: Not Documenting Chain of Custody

```
❌ WRONG:
"I collected the disk image, but didn't write down who handled it, when, or verify hashes"
(In a legal case, evidence is rejected)

✅ RIGHT:
"Disk image collected 2024-01-15 14:30 by Jane Analyst
Original hash: SHA256:a1b2c3d4e5f6...
Image hash:   SHA256:a1b2c3d4e5f6... ✓ VERIFIED
Sealed by: John Manager (2024-01-15 15:00)
Accessed by: Sarah DFIR (2024-01-16 09:00) for analysis"
(Legally defensible, reproducible)

Consequence: Evidence thrown out, case dismissed, reputation damaged
```

---

### Mistake #4: Ignoring Volatility

```
❌ WRONG:
"System is compromised. Let me shut it down to image the disk"
(RAM is lost forever! Malware in memory = gone!)

✅ RIGHT:
"System is compromised. Quick priority:
1. Dump memory NOW (while running)
2. Collect volatile data (netstat, tasklist, open files)
3. THEN image disk"
(Memory often reveals malware that doesn't hit disk)

Consequence: Miss malware-in-RAM-only attacks, incomplete investigation
```

---

## 🧪 Practice Scenario

**Scenario: Insider Threat Investigation**

```
You receive a ticket:
"Analyst suspects employee ALICE may be exfiltrating customer data.
Alice has access to Customer_Database. Last night, IT noticed unusual
network traffic from her workstation (large outbound transfer, 500MB+).
Alice's laptop is now isolated. Investigate within 4 hours."

YOUR INVESTIGATION (answer these questions):

1. SCOPING:
   - What evidence sources do you need?
   - What's your priority (volatile first)?
   - What are you looking for?

2. COLLECTION:
   - Memory dump (why is this critical in insider threat case?)
   - Browser history (where did Alice send data?)
   - Email (did she plan this? Any communications?)
   - File system (did she stage data? When?)
   - Network (which C2 did she contact? OR personal cloud drive?)

3. TIMELINE:
   - When did unusual activity start?
   - Was it sudden spike or gradual?
   - Does it correlate with known events (termination notice? Angry?)?

4. ANALYSIS:
   - Did Alice manually copy files? OR use malware/script?
   - How many files? What data? PII? Trade secrets?
   - How long has this been going on?

5. ROOT CAUSE:
   - Is Alice really exfiltrating? OR is it legitimate work?
   - Did her account get compromised? (check failed logins before spike)
   - Is the network traffic actually FROM her? (could be malware on her machine)

6. REPORT:
   - Evidence to support your conclusions
   - Timeline showing progression
   - Recommendations (legal vs technical)
```

**Expected Findings:**

```
One hour into investigation:

Timeline analysis:
├─ 2024-01-14 17:00:00 → Alice sends email to personal Gmail account
│  └─ Subject: "Starting new job at competitors.com next week"
│
├─ 2024-01-14 18:30:00 → Alice uploads 500MB to Google Drive
│  └─ File: "Customer_Database_20240114.zip"
│  └─ Hash: SHA256:abc123... (malware? no, just ZIP)
│
├─ 2024-01-14 19:00:00 → Alice deletes files from her staging area
│  └─ Tries to hide evidence
│
└─ 2024-01-14 19:30:00 → Alice logs out, leaves office

CONCLUSION:
✓ Alice intentionally exfiltrated data
✓ She's planning to take it to competitors.com
✓ Not a malware case, but INSIDER THREAT
✓ Action: Legal + HR involvement (not just IT incident response)
```

---

## 🎯 Interview Questions You Might Get

### Level 1 (Entry-Level)

**Q1: "What's the difference between Digital Forensics and Incident Response?"**
> "Digital Forensics is post-attack investigation: 'What happened, exactly?' Incident Response is during/after: 'Stop the attack, contain damage, recover systems.' IR is real-time decisions, Forensics is detailed analysis afterward."

**Q2: "Why do we preserve chain of custody?"**
> "So evidence is legally defensible, technically reliable, and reproducible. If chain is broken, evidence is inadmissible in court and may be compromised."

**Q3: "What's 'root cause' vs 'first suspicious log'?"**
> "Root cause is the first action that succeeded (initial access or exploit). First suspicious log is when we detected something was wrong. They're different times."

### Level 2 (Mid-Level)

**Q1: "Walk me through how you'd investigate a suspected insider threat."**
> "1) Scope: What data might they access? Which systems? 2) Collect: Memory, browser history, email, file system. 3) Timeline: When did unusual activity start? 4) Analyze: Was it manual copy or malware? 5) Determine: Is it really insider threat or compromised account? 6) Report: Evidence-based conclusion."

**Q2: "You find a file modified at 3 AM with unusual extension (.exe in temp folder). It's definitely malware. How do you proceed?"**
> "WRONG APPROACH: Execute it to see what it does. RIGHT APPROACH: 1) Don't touch it. 2) Image the disk (preserve evidence). 3) Hash the file. 4) Analyze in sandbox or using Volatility if in memory. 5) Trace lateral movement: what did this malware do? Where did it come from?"

**Q3: "Disk image shows 47,000 deleted files in unallocated space. How do you recover and analyze them?"**
> "Use FTK Imager or similar to recover deleted files from unallocated space. Hash each. Run YARA signatures or check for known malware hashes. Timeline them (deleted when?). This might show attacker's staging area or data that was stolen then deleted."

### Level 3 (Senior / Experienced)

**Q1: "You're investigating a breach. The attacker's been there for 6 months. Logs only go back 30 days. How do you determine initial access point?"**
> "1) Analyze persistence mechanisms (registry, scheduled tasks, WMI) — when were they created? 2) Look for accounts created in last 6 months (backdoor accounts). 3) Find earliest lateral movement evidence. 4) Correlate with vendor advisories (which CVE was probably exploited when?). 5) Interview: when did systems start acting weird? 6) Examine Change Management logs (was there an unusual change 6 months ago?). You can't see all logs, but you can infer timeline from other evidence."

**Q2: "Malware was executing in memory but never hit disk. How do you analyze this and prove what it did?"**
> "1) Memory dump is golden. Use Volatility: pslist (find process), vaddump (extract address space), disasm (disassemble injected code). 2) Analyze API calls the malware made (what Win32 functions did it call?). 3) Look for strings in memory (C2 domain, file paths, registry keys). 4) Cross-reference with IDS/IPS logs (which IPs did process connect to?). 5) Sandbox testing: if you recovered code, detonate in isolated environment to confirm behavior. The memory dump IS the evidence."

**Q3: "You have two hypotheses: (A) Attacker used known CVE, OR (B) Attacker had insider access. Timeline could support either. How do you differentiate?"**
> "1) If CVE exploitation: would see suspicious process creation, privilege escalation attempt, unusual parent-child relationships. 2) If insider: would see normal login, normal file access patterns, but unusual timing or unusual files accessed. 3) Check: was there a patch for the CVE? If system is patched, rules out CVE. 4) Check failed login attempts before breach: if 1000s of failed logins (brute force), insider unlikely. 5) Interview: does attacker's behavior match any current/former employees? 6) Motivation: what data was stolen? Does it align with insider's access level? You build probability, present evidence for both, let leadership decide."

---

## 🔗 How DFIR Connects to Everything

```
Detection Engineering
├─ Finds the attack (SIEM alert)
└─ DFIR analyzes it, finds root cause
   └─ Detection Engineer writes rule to catch similar attacks in future

Incident Response
├─ Decides in real-time (isolate? not yet?)
└─ DFIR does detailed investigation
   └─ IR uses DFIR findings for containment decisions

Threat Hunting
├─ Hunts for suspicious patterns
└─ If finds something, escalates to DFIR
   └─ DFIR confirms it's real attack or false positive

Network Security
├─ Logs all traffic
└─ DFIR analyzes firewall/IDS logs for C2 connections
   └─ Used to trace attacker's exfiltration path

Endpoint Security (EDR/AV)
├─ Blocks malware, records behavior
└─ DFIR analyzes EDR logs for attack timeline
   └─ Combined with disk/memory forensics = complete picture

Compliance (SOC 2, HIPAA, PCI-DSS)
├─ Requires incident investigation
└─ DFIR provides documented proof
   └─ "Here's the timeline, chain of custody, evidence"
```

---

## 💾 TL;DR - Quick Reference

### The DFIR Process
```
1. SCOPING → What happened? How bad?
2. COLLECTION → Volatile (memory) → Non-volatile (disk) → Network
3. TIMELINE → Merge all timestamps, find sequences
4. ANALYSIS → Root cause, impact, attack chain
5. REPORTING → Evidence-based conclusions + recommendations
6. PREVENTION → Detection Engineering writes new rules
```

### Key Metrics
```
Chain of Custody: Maintained ✓
Evidence Hash Verified: ✓
Timeline Reproducible: ✓
Attack Sequence Clear: ✓
Root Cause Identified: ✓
→ Investigation successful
```

### Tools Cheat Sheet
```
Imaging: FTK Imager, dd, Guymager
Memory Analysis: Volatility3, DumpIt
Timeline: Plaso (log2timeline), Timeline Explorer
Registry: RegRipper, Registry Explorer
Logs: Windows Event Viewer, Splunk, ELK
```

### Common Mistakes
```
1. ❌ Modify evidence → Work on copies only
2. ❌ Miss volatile data → Dump memory FIRST
3. ❌ Skip chain of custody → Document EVERYTHING
4. ❌ Confuse sequences → Build multi-source timeline
```

---

## 📌 Real-World Reality

### Case: Wannacry Ransomware (2017)

```
Investigation after attack:

Timeline reconstruction:
├─ 2017-05-12 14:32:00 → Vulnerable Windows system infected via EternalBlue exploit
├─ 2017-05-12 14:35:00 → Ransomware payload executes, starts encryption
└─ 2017-05-12 15:00:00 → Company pays ransom (then starts investigation)

DFIR findings:
├─ Root cause: Unpatched Windows (MS17-010 patch available for 2 months!)
├─ Persistence: None found (ransomware didn't install backdoor)
├─ Lateral movement: Infected multiple systems on same network (poor segmentation)
├─ Impact: 200,000+ files encrypted across 5 servers

Lessons learned:
├─ Patch management is critical (this was preventable)
├─ Network segmentation needed (ransomware shouldn't cross boundaries)
└─ Backups are better than ransom (restore time 72 hours vs ransom + decryption uncertainty)
```

### Case: Insider Threat (Real SOC)

```
Scenario: Employee fired, suspected data theft

DFIR Timeline:
├─ 2024-01-10 → Employee notified of termination
├─ 2024-01-10 15:00:00 → Employee accesses "Confidential_Formulas" folder (unusual)
├─ 2024-01-10 16:30:00 → Large file upload to personal OneDrive (500MB)
├─ 2024-01-10 18:00:00 → Employee logs out, leaves office
└─ 2024-01-11 → Investigation begins

Forensic evidence:
├─ Browser history shows OneDrive login (personal account)
├─ File staging in %TEMP% (compression before upload)
├─ Deletion attempts (Shift+Delete, not recovery possible)
└─ Email to competitor (found in Outlook cache)

Conclusion:
✓ Confirmed insider threat
✓ Data exfiltrated to personal account (could be accessed from anywhere)
✓ Proof for legal action

Action:
├─ Legal: Lawsuit against employee
├─ Technical: Change credentials, audit cloud storage
└─ Process: Implement USB blocking, DLP (Data Loss Prevention) on cloud uploads
```

---

## 📚 What's Next

1. **Learn Volatility** → Memory forensics (most attacks leave traces in RAM first)
2. **Practice timeline building** → Get comfortable merging events from multiple sources
3. **Set up forensic lab** → Old laptop, Windows image, tools installed
4. **Do tabletop exercises** → Simulate breach, practice DFIR workflow
5. **Study MITRE ATT&CK** → Map your forensic findings to attack framework

---

## 📌 Remember

```
┌────────────────────────────────────────────────────────────┐
│                                                            │
│  DFIR ≠ Just looking at logs                             │
│  DFIR = Structured investigation: Collect → Timeline →   │
│         Analyze → Report → Prevent                        │
│                                                            │
│  Evidence without chain of custody = Useless             │
│  Timeline without correlation = Meaningless              │
│  Report without recommendations = Incomplete             │
│                                                            │
│  Success is when you can say with certainty:            │
│  "This is EXACTLY what happened, when, and why"         │
│  AND you can PROVE it with evidence                      │
│                                                            │
└────────────────────────────────────────────────────────────┘
```

---

**Last Updated:** 2024
**Version:** 1.0
**For:** Blue Team Students - TripleTen Bootcamp
